# port
server:
  port: 9555


spring:
  # database connection
  datasource:
    url: jdbc:mysql://studentcenter.mysql.database.azure.com:3306/studentcenter
    username: scenter
    password: StudentCenter9555
    driver-class-name: com.mysql.jdbc.Driver
  # thymeleaf config
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML